version: '3.8'

services:
  tracklab:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./thesis_sn-gamestate:/app/thesis_sn-gamestate
      - ./thesis_tracklab:/app/thesis_tracklab
      - ./data:/app/data
      - ./outputs:/app/outputs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    tty: true 