version: '3.8'

services:
  tracklab:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./thesis_sn-gamestate:/app/thesis_sn-gamestate
      - ./thesis_tracklab:/app/thesis_tracklab
      - ./data:/app/data
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    tty: true 